<!-- view_with_pdf.php -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Preview</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
        }
        .content {
            margin-top: 20px;
        }
        iframe {
            width: 100%;
            height: 500px;
            border: none;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>PDF Preview</h1>
    <div class="content">
        <p>This is a preview of the PDF document below.</p>
    </div>

    <!-- Embed the PDF file stored in the public/uploads directory -->
    <iframe src="<?= base_url('uploads/Admission_Slip.pdf'); ?>" title="PDF Preview"></iframe>

    <div class="footer">
        <p>Generated by CodeIgniter 4</p>
    </div>
</body>
</html>
